### ISSUE TITLE
Does not work on Linux

### ISSUE THREAD

**Issue by gnufied** [code-mancers/rbkit-electron-redux#18]
I think file names being used are assumbed to be case insensitive and hence this I see following error when trying to run this on Linux:

![selection_013](https://cloud.githubusercontent.com/assets/278/15788704/cd76319c-2996-11e6-8a41-c11657ab9395.png)

**Comment by emilsoman** [comment]
@gnufied thanks for reporting. This will be fixed tomorrow.

**Comment by nithinbekal** [comment]
@emilsoman @gnufied This was fixed in #19. Could you please confirm and close this issue?

**Comment by emilsoman** [comment]
Thanks @nithinbekal @juliatjoy ❤️
